### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by mtzro2003** [davorf/VoiceHAB#2]
Hi!

I made some modifications (improvements in my humble opinion 😄 )
How do I upload the changes so you can see and (maybe) approve?
I cloned the repository on my RPi with "git clone https://github.com/davorf/VoiceHAB" and edited the files there...

Should I create my own repository?
Fork this one?
Pull request?
Dunno... but I attach a zip with the whole directory.
[VoiceHAB.zip](https://github.com/davorf/VoiceHAB/files/704013/VoiceHAB.zip)

**Comment by davorf** [comment]
Hello!

Since I'm at work right now. I just took a quick look at the code you've sent. As far as I can see, there is logging instead of print, separate audio player module, playing beep when speech input is required and some modifications to recognizer and microphone threshold. Could you tell me what are the benefits of using logging instead of print? I see there is part of the code under comments (recognizer adjusting for ambient noise and microphone threshold) - is it better to call it every time, because I do that while initializing module, because it takes some time, and it slows down whole process.  Regarding separate module for playing sounds, it is definitely a really good idea. Are there any more changes that I might have missed? 

Since I prefer my own code formatting and naming (it makes code maintenance a lot easier for me), I would like to implement these changes, but I'll do it by extracting changes and implementing them, rather then merging pull request and reformatting it afterwards. 

Best regards,
Davor

**Comment by mtzro2003** [comment]
Well, the modifications I made are just for testing mostly and maybe improving (or that's what I would like to believe :smile:)
Regarding the logging... I found it useful to run with --log=info or even --log=debug to see what's going on... With debug it will even print out the URL calls for the speech-to-text engines.
Regarding the commented lines... I observed that sometimes it not recognizing the wakeup word and I thought maybe re-adjusting for the noise level will improve that - it is still under testing, that's why they are now commented. I'm in the process of investigating further options for speech_recognition ([https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst](url))
You can do whatever you want with my modifications and that includes ignoring them altogether :smile:

**Comment by davorf** [comment]
Hello!

Well, separate sound player is definitely an improvement. I like this logging option too, but I was wondering why do you replace new line character? There shouldn't be any new lines in these messages. I will include logging too, but, since you are not sure if microphone threshold and recognizer adjustment are actually an improvement, I will leave that change out. I hope I will have some free time tonight to implement these changes (and, maybe, start working on Voice Authorization - if it's still available as free Microsoft API). Thank you for your contribution. 

Best regards,
Davor

**Comment by mtzro2003** [comment]
I replace the new line because logging the message prints it followed by an empty line.

**Comment by davorf** [comment]
Hello!

I've added logging and separate sound player as you've suggested. I've also changed __main__.py to intercept CTRL + C as an exit command (to avoid displaying error message, and used logging.debug instead). I've used print instead of raising error, because it looks more user-friendly than error message. 

I will close this issue now, but, if you have any others suggestions or problems, you can open a new one. Thank you for your contribution. 

Best regards,
Davor
